# Generated by Django 5.1.3 on 2024-11-22 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_of_birth', models.DateField()),
                ('country', models.CharField(max_length=100)),
                ('account_type', models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium'), ('corporate', 'Corporate')], max_length=50)),
                ('account_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('account_open_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('risk_tolerance', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=50)),
                ('account_currency', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'clients',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4)),
                ('transaction_date', models.DateTimeField()),
                ('stock_ticker', models.CharField(max_length=10)),
                ('stock_name', models.CharField(max_length=255)),
                ('shares', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(max_length=3)),
                ('transaction_status', models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('failed', 'Failed')], max_length=50)),
                ('transaction_channel', models.CharField(choices=[('online', 'Online'), ('branch', 'Branch'), ('ATM', 'ATM')], max_length=50)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.client')),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
    ]
