# Generated by Django 5.1.3 on 2024-11-24 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_etljob'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE MATERIALIZED VIEW client_transaction_summary AS
            SELECT 
                t.client_id,
                COUNT(*) AS total_transactions,
                SUM(CASE WHEN t.transaction_type = 'buy' THEN t.amount ELSE 0 END) AS total_spent,
                SUM(CASE WHEN t.transaction_type = 'sell' THEN ABS(t.amount) ELSE 0 END) AS total_gained
            FROM 
                transactions t
            GROUP BY 
                t.client_id;
            """,
            reverse_sql="DROP MATERIALIZED VIEW IF EXISTS client_transaction_summary;"
        )
    ]
