# Generated by Django 5.1.3 on 2024-11-24 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20241124_2247'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientTransactionSummary',
            fields=[
                ('client_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('total_transactions', models.IntegerField()),
                ('total_spent', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_gained', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'db_table': 'client_transaction_summary',
                'managed': False,
            },
        ),
    ]
